stages:
  - build
  - test
  - deploy


variables:
  MAVEN_OPTS: >
    -Dmaven.test.skip=true
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Djar.finalName=$ARCHIVE_NAME


build:
  stage: build
  tags:
    # - dind
    - runner-java
  script: 
    - mvn $MAVEN_OPTS clean package
    - tar xz "$ARCHIVE_NAME.tar.xz" $ARCHIVE_NAME 
  artifacts:
    expire_in: 1 hour
    paths:
      - "$ARCHIVE_NAME.tar.xz"

archive:
  image: lgatica/openssh-client
  stage: deploy
  tags:
    # - dind
    - runner-java
  script:
    - echo "$ARCHIVE_PKEY" > archive_pkey
    - chmod 400 archive_pkey
    - chmod 700 .
    - echo "put -rp $ARCHIVE_PATH/$ARCHIVE_NAME.tar.xz $ARCHIVE_NAME.tar.xz" > archive_batch
    - >
      sftp
      -i archive_pkey
      -o UserKnownHostsFile=/dev/null
      -o StrictHostKeyChecking=no
      -b archive_batch
      $ARCHIVE_USER@$ARCHIVE_HOST
  only:
    - dev