image: maven:3-jdk-8

stages:
  - build
  - test
  - deploy


variables:
  MAVEN_OPTS: >
    -Dmaven.test.skip=true
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
  ARCHIVE_NAME: planning-jar
  BUILD_OUTPUT: target/calendarproject-1.0.jar


build:
  stage: build
  tags:
    # - dind
    - runner-java
  script: 
    - mvn $MAVEN_OPTS clean package
    - tar cfJ "$ARCHIVE_NAME.tar.xz" $BUILD_OUTPUT
  artifacts:
    expire_in: 1 hour
    paths:
      - "$ARCHIVE_NAME.tar.xz"

archive:
  image: lgatica/openssh-client
  stage: deploy
  tags:
    # - dind
    - runner-java
  script:
    - echo "$ARCHIVE_PKEY" > archive_pkey
    - chmod 400 archive_pkey
    - chmod 700 .
    - >
      echo
      "put -rp $ARCHIVE_PATH/$ARCHIVE_NAME.tar.xz $ARCHIVE_NAME.tar.xz"
      > archive_batch
    - >
      sftp
      -i archive_pkey
      -o UserKnownHostsFile=/dev/null
      -o StrictHostKeyChecking=no
      -b archive_batch
      $ARCHIVE_USER@$ARCHIVE_HOST
  only:
    - dev